apiVersion: v1
kind: Service
metadata:
  name: wavecafe-service
  namespace: dev
spec:
  # Expose the application outside the Kubernetes cluster
  type: NodePort
  # Select Pods with this label
  selector:
    app: wavecafe
  ports:
    - protocol: TCP
      # Service port inside the Kubernetes cluster
      port: 80
      # Application/Container is running on port 80
      targetPort: 80
      # External port exposed on every Kubernetes Node
      nodePort: 30080
